### ISSUE TITLE
Error: register failed, the sensor listeners size has exceeded the maximum limit 128

### ISSUE THREAD

**Issue by rpopovych** [Doko-Demo-Doa/react-native-shake#44]
Getting the error below on Android devices.

One thing I noticed is that there is a [stop](https://github.com/Doko-Demo-Doa/react-native-shake/blob/1dd3ce16b30d66f796d369160ad494aa6b8b00f0/android/src/main/java/com/clipsub/RNShake/CustomShakeDetector.java#L77) method on the detector, but nothing is calling it.

Has anyone ran into this issue?

```
Fatal Exception: java.lang.IllegalStateException: register failed, the sensor listeners size has exceeded the maximum limit 128
       at android.hardware.SystemSensorManager.registerListenerImpl(SystemSensorManager.java:186)
       at android.hardware.SensorManager.registerListener(SensorManager.java:833)
       at android.hardware.SensorManager.registerListener(SensorManager.java:740)
       at com.clipsub.RNShake.CustomShakeDetector.start(CustomShakeDetector.java:68)
       at com.clipsub.RNShake.RNShakeEventModule.<init>(RNShakeEventModule.java:27)
       at com.clipsub.RNShake.RNShakeEventPackage.createNativeModules(RNShakeEventPackage.java:17)
       at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
       at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
       at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1476)
       at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1447)
       at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1341)
       at com.facebook.react.ReactInstanceManager.access$1200(ReactInstanceManager.java:138)
       at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1111)
       at java.lang.Thread.run(Thread.java:1012)
```

**Comment by Doko-Demo-Doa** [comment]
I didn't. It should be resolved in the latest version though.
